### ISSUE TITLE
What is the location of the files cache?

### ISSUE THREAD

**Issue by via-guy** [samuelabreu/cocoapods-s3-download#6]
I want to re-download a file but it's been cached somewhere and I can't see where. Where is it saved?

**Comment by samuelabreu** [comment]
You can check https://guides.cocoapods.org/using/faq.html#can-i-change-the-default-cocoapods-repositories-folder

**Comment by via-guy** [comment]
Thanks. Yes, I eventually managed to download the `~/.cocoapods` cache as well as the `Pods` folder itself and that did the trick...
